export const MOCK_USERS = [
  {
    id: '1',
    name: 'John Carter',
    email: 'john@google.com',
    avatar: 'https://github.com/shadcn.png',
    phone: '(414) 907 - 1274',
    location: 'United States',
    company: {
      name: 'Google',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png',
    },
    status: 'Online',
  },
  {
    id: '2',
    name: 'Sophie Moore',
    email: 'sophie@webflow.com',
    avatar: 'https://github.com/shadcn.png',
    phone: '(240) 480 - 4277',
    location: 'United Kingdom',
    company: {
      name: 'Webflow',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Webflow_logo.svg/512px-Webflow_logo.svg.png',
    },
    status: 'Offline',
  },
  {
    id: '3',
    name: 'Matt Cannon',
    email: 'matt@facebook.com',
    avatar: 'https://github.com/shadcn.png',
    phone: '(318) 698 - 9889',
    location: 'Australia',
    company: {
      name: 'Facebook',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/2021_Facebook_icon.svg/512px-2021_Facebook_icon.svg.png',
    },
    status: 'Offline',
  },
  {
    id: '4',
    name: 'Graham Hills',
    email: 'graham@twitter.com',
    avatar: 'https://github.com/shadcn.png',
    phone: '(540) 627 - 3890',
    location: 'India',
    company: {
      name: 'Twitter',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Logo_of_Twitter.svg/512px-Logo_of_Twitter.svg.png',
    },
    status: 'Online',
  },
  {
    id: '5',
    name: 'Sandy Houston',
    email: 'sandy@youtube.com',
    avatar: 'https://github.com/shadcn.png',
    phone: '(440) 410 - 3848',
    location: 'Canada',
    company: {
      name: 'YouTube',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/YouTube_full-color_icon_%282017%29.svg/512px-YouTube_full-color_icon_%282017%29.svg.png',
    },
    status: 'Offline',
  },
  {
    id: '6',
    name: 'Andy Smith',
    email: 'andy@reddit.com',
    avatar: 'https://github.com/shadcn.png',
    phone: '(504) 458 - 3268',
    location: 'United States',
    company: {
      name: 'Reddit',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Reddit_icon.svg/512px-Reddit_icon.svg.png',
    },
    status: 'Online',
  },
  {
    id: '7',
    name: 'Lilly Woods',
    email: 'lilly@spotify.com',
    avatar: 'https://github.com/shadcn.png',
    phone: '(361) 692 - 1819',
    location: 'Australia',
    company: {
      name: 'Spotify',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Spotify_logo_without_text.svg/512px-Spotify_logo_without_text.svg.png',
    },
    status: 'Offline',
  },
  {
    id: '8',
    name: 'Patrick Meyer',
    email: 'patrick@pinterest.com',
    avatar: 'https://github.com/shadcn.png',
    phone: '(760) 582 - 5670',
    location: 'United Kingdom',
    company: {
      name: 'Pinterest',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Pinterest-logo.png/512px-Pinterest-logo.png',
    },
    status: 'Online',
  },
  {
    id: '9',
    name: 'Frances Willen',
    email: 'frances@twitch.com',
    avatar: 'https://github.com/shadcn.png',
    phone: '(216) 496 - 5864',
    location: 'Canada',
    company: {
      name: 'Twitch',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Twitch_Glitch_Logo_Purple.svg/512px-Twitch_Glitch_Logo_Purple.svg.png',
    },
    status: 'Offline',
  },
  {
    id: '10',
    name: 'Ernest Houston',
    email: 'ernest@linkedin.com',
    avatar: 'https://github.com/shadcn.png',
    phone: '(704) 339 - 8813',
    location: 'India',
    company: {
      name: 'LinkedIn',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/512px-LinkedIn_logo_initials.png',
    },
    status: 'Offline',
  },
]
